apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: demo-app
spec:
  ports:
    - name: "3000"
      port: 3000            # The port the service listens on
      targetPort: 3000      # The port on the pod to which the traffic is forwarded
  selector:
    app: demo-app
  type: LoadBalancer
